/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricardo
 */
public class Tramas extends javax.swing.JFrame {

    DefaultTableModel modeloTabla;
    int indice;
    File archivoElegido;

    /**
     * Creates new form Tramas
     */
    public Tramas() {
        initComponents();
        modeloTabla = new DefaultTableModel(new String[]{
            "Nombre", "Tamaño", "Dato"
        }, 1);
        tblTrama.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTrama = new javax.swing.JTextArea();
        btnLeerTrama = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTrama = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSubir = new javax.swing.JButton();
        btnBajar = new javax.swing.JButton();
        btnCrearTrama = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        meAbrir = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        meGuardarComo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        meSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tramas");

        jLabel1.setText("Tramas:");

        txtTrama.setColumns(20);
        txtTrama.setLineWrap(true);
        txtTrama.setRows(5);
        jScrollPane1.setViewportView(txtTrama);

        btnLeerTrama.setText("Leer Trama");
        btnLeerTrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerTramaActionPerformed(evt);
            }
        });

        tblTrama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Tamaño", "Dato"
            }
        ));
        tblTrama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTramaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTrama);

        btnInsertar.setText("Insertar Nueva");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnSubir.setText("Subir");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        btnBajar.setText("Bajar");
        btnBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajarActionPerformed(evt);
            }
        });

        btnCrearTrama.setText("Crear Trama");
        btnCrearTrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTramaActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        meAbrir.setText("Abrir");
        meAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(meAbrir);

        jMenuItem2.setText("Guardar");
        jMenu1.add(jMenuItem2);

        meGuardarComo.setText("Guardar como");
        meGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meGuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(meGuardarComo);
        jMenu1.add(jSeparator1);

        meSalir.setText("Salir");
        meSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meSalirActionPerformed(evt);
            }
        });
        jMenu1.add(meSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSubir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBajar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLeerTrama, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCrearTrama, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeerTrama)
                    .addComponent(btnCrearTrama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBajar)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        modeloTabla.addRow(new String[]{null, null, null});
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        try {
            modeloTabla.removeRow(indice);
        } catch (java.lang.ArrayIndexOutOfBoundsException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void tblTramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTramaMouseClicked
        // TODO add your handling code here:
        indice = tblTrama.getSelectedRow();
    }//GEN-LAST:event_tblTramaMouseClicked

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
        if (indice != 0) {
            Object nombreSel = modeloTabla.getValueAt(indice, 0);
            Object tamanoSel = modeloTabla.getValueAt(indice, 1);
            Object datoSel = modeloTabla.getValueAt(indice, 2);
            modeloTabla.setValueAt(modeloTabla.getValueAt((indice - 1), 0), indice, 0);
            modeloTabla.setValueAt(modeloTabla.getValueAt((indice - 1), 1), indice, 1);
            modeloTabla.setValueAt(modeloTabla.getValueAt((indice - 1), 2), indice, 2);

            modeloTabla.setValueAt(nombreSel, (indice - 1), 0);
            modeloTabla.setValueAt(tamanoSel, (indice - 1), 1);
            modeloTabla.setValueAt(datoSel, (indice - 1), 2);

            tblTrama.setRowSelectionInterval(indice - 1, indice - 1);
            indice--;
        }
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajarActionPerformed
        // TODO add your handling code here:
        if (indice != (modeloTabla.getRowCount() - 1)) {
            Object nombreSel = modeloTabla.getValueAt(indice, 0);
            Object tamanoSel = modeloTabla.getValueAt(indice, 1);
            Object datoSel = modeloTabla.getValueAt(indice, 2);
            modeloTabla.setValueAt(modeloTabla.getValueAt((indice + 1), 0), indice, 0);
            modeloTabla.setValueAt(modeloTabla.getValueAt((indice + 1), 1), indice, 1);
            modeloTabla.setValueAt(modeloTabla.getValueAt((indice + 1), 2), indice, 2);

            modeloTabla.setValueAt(nombreSel, (indice + 1), 0);
            modeloTabla.setValueAt(tamanoSel, (indice + 1), 1);
            modeloTabla.setValueAt(datoSel, (indice + 1), 2);
            tblTrama.setRowSelectionInterval(indice + 1, indice + 1);
            indice++;
        }
    }//GEN-LAST:event_btnBajarActionPerformed

    private void btnLeerTramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerTramaActionPerformed
        // TODO add your handling code here:
        int len;
        String ttrama = txtTrama.getText();
        int tcursor = 0;
        int fin = 0;
        for (int i = 0; modeloTabla.getRowCount() > i; i++) {
            fin += Integer.parseInt((String) modeloTabla.getValueAt(i, 1));
            modeloTabla.setValueAt(ttrama.substring(tcursor, fin), i, 2);
            tcursor += Integer.parseInt((String) modeloTabla.getValueAt(i, 1));
        }
    }//GEN-LAST:event_btnLeerTramaActionPerformed

    private void btnCrearTramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTramaActionPerformed
        // TODO add your handling code here:
        txtTrama.setText(null);
        int ini = 0;
        int fin = 0;
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            fin = Integer.parseInt((String) modeloTabla.getValueAt(i, 1));
            txtTrama.append((String) modeloTabla.getValueAt(i, 2).toString().substring(ini, fin));

        }
    }//GEN-LAST:event_btnCrearTramaActionPerformed

    private void meAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meAbrirActionPerformed
        // TODO add your handling code here:
        //Crear un objeto FileChooser
        JFileChooser fc = new JFileChooser();
        //Mostrar la ventana para abrir archivo y recoger la respuesta
        //En el parámetro del showOpenDialog se indica la ventana
        //  al que estará asociado. Con el valor this se asocia a la
        //  ventana que la abre.

        int respuesta = fc.showOpenDialog(this);
        //Comprobar si se ha pulsado Aceptar
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            archivoElegido = fc.getSelectedFile();
            FileReader f = null;
            try {
                 f = new FileReader(archivoElegido);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Tramas.class.getName()).log(Level.SEVERE, null, ex);
            }
           BufferedReader b = new BufferedReader(f);
            String cadena;
            DefaultTableModel df = (DefaultTableModel)tblTrama.getModel();
            df.setRowCount(0);
            
            try {
                while((cadena = b.readLine())!=null) {
                    StringTokenizer tokens=new StringTokenizer(cadena, ",");
                    String[] lista = new String[3] ;
                    int i = 0;
                    	while(tokens.hasMoreTokens()){
                            lista[i] = tokens.nextToken();
                        i++; 
                        }
                       lista[2] = String.format("%1$-"+lista[1]+"s",lista[2]);
                        df.addRow(lista);
                    
                    
                }     } catch (IOException ex) {
                Logger.getLogger(Tramas.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                b.close();
            } catch (IOException ex) {
                Logger.getLogger(Tramas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_meAbrirActionPerformed

    private void meSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_meSalirActionPerformed

    private void meGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meGuardarComoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //Crear un objeto FileChooser
        JFileChooser fc = new JFileChooser();
        //Mostrar la ventana para abrir archivo y recoger la respuesta
        //En el parámetro del showOpenDialog se indica la ventana
        //  al que estará asociado. Con el valor this se asocia a la
        //  ventana que la abre.

        int respuesta = fc.showSaveDialog(this);
        //Comprobar si se ha pulsado Aceptar
        if (respuesta == JFileChooser.APPROVE_OPTION) {

        }
    }//GEN-LAST:event_meGuardarComoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tramas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCrearTrama;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLeerTrama;
    private javax.swing.JButton btnSubir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem meAbrir;
    private javax.swing.JMenuItem meGuardarComo;
    private javax.swing.JMenuItem meSalir;
    private javax.swing.JTable tblTrama;
    private javax.swing.JTextArea txtTrama;
    // End of variables declaration//GEN-END:variables
}
